### ISSUE TITLE
When leader fails local put, we should step down

### ISSUE THREAD

**Issue by jtuple** [basho/riak_ensemble#2]
When the leader fails to write a value locally in `put_obj`, the leader should step down.

See TODO comment on [here](https://github.com/basho/riak_ensemble/blob/jdb-wip-2.0/src/riak_ensemble_peer.erl#L1062) and pull-request comment [here](https://github.com/basho/riak_ensemble/pull/1#discussion_r7977292).

**Comment by andrewjstone** [comment]
Closing. #27 is the fix. Just needs review.
